# hydra:
#   run:
#     dir: ./my_output_dir  # save outputs to custom dir

root_dir: ${hydra:runtime.cwd}



dataset_name: owt  # `TinyStories` or `owt`, change as needed
exp_name: cs336_lm_${dataset_name}

dataset_split: train
dat_dir: ${root_dir}/data/${dataset_name}/dat

tokenizer_dir: ${root_dir}/tokenizers/${dataset_name}_${dataset_split}/ # save path for tokenizer
vocab_path: ${tokenizer_dir}/vocab.pkl
merges_path: ${tokenizer_dir}/merges.pkl
special_tokens: ["<|endoftext|>"]

vocab_size_map:
  TinyStories: 10_000
  owt: 32_000

# 根据 dataset_name 动态设置 vocab_size
vocab_size: ${vocab_size_map.${dataset_name}}


train:
  project_name: ${exp_name}

  train_data_path: ${dat_dir}/train.dat
  valid_data_path: ${dat_dir}/valid.dat

  ckpt_path: "checkpoints/${exp_name}" # save path for both first train and resume train
  lr: 0.0005
  min_lr: 0.0001
  beta1: 0.9
  beta2: 0.95
  epsilon: 1e-8
  weight_decay: 0.01
  batch_size: 32
  context_length: 256
  train_steps: 5000
  clip_grad_norm: 1.0
  warmup_iters: 500
  cosine_iters: 5000
  log_interval: 100
  eval_interval: 1000
  val_batches: 20
  checkpoint_freq: 15000
  resume_checkpoint: null   # load checkpoint from current hydra run dir
  use_compile: False
  device: "cuda"

model_type: cs336_lm
model:
  vocab_size: ${vocab_size_map.${dataset_name}}
  batch_size: 32
  context_length: 256
  d_model: 512
  num_layers: 4
  num_heads: 16
  d_ff: 1344
  rope_theta: 10000.0
  device: "cuda"
  checkpoint_dir: ${root_dir}/checkpoints/${exp_name}
